'use strict';
const $=id=>document.getElementById(id);let labs={},selected='hh',last=null;
const token=document.querySelector('meta[name="lab-token"]').content;
function text(tag,value){const e=document.createElement(tag);e.textContent=value;return e;}
function fmt(x){return typeof x==='number'?(Number.isInteger(x)?String(x):(Math.abs(x)<1e-3||Math.abs(x)>1e5?x.toExponential(4):x.toFixed(5))):String(x);}
function menu(){const q=$('filter').value.toLowerCase();$('labs').replaceChildren();for(const [key,s]of Object.entries(labs)){if(!(key+' '+s.title).toLowerCase().includes(q))continue;const b=text('button',s.title);b.dataset.lab=key;b.className=key===selected?'active':'';b.append(text('small',s.book_sections.join(' · ')));b.onclick=()=>select(key);$('labs').append(b);}}
function select(key){last=null;$('download').disabled=true;$('status').textContent='Ready';selected=key;const s=labs[key];$('workspace').hidden=false;$('fit-workspace').hidden=true;$('book-workspace').hidden=true;$('result').hidden=true;$('title').textContent=s.title;$('question').textContent=s.question;$('method').textContent=s.method;$('anchor').textContent='BOOK SECTIONS '+s.book_sections.join(' · ');$('parameters').replaceChildren();$('error').textContent='';for(const [name,p]of Object.entries(s.parameters)){const cell=document.createElement('div'),label=text('label',name.replaceAll('_',' '));label.htmlFor='p-'+name;const input=document.createElement('input');input.type='number';input.id='p-'+name;input.name=name;input.min=p.min;input.max=p.max;input.step=p.type==='integer'?'1':'any';input.value=p.default;input.required=true;cell.append(label,input,text('div',`${p.unit} · ${p.min} to ${p.max}`));cell.lastChild.className='hint';$('parameters').append(cell);}menu();}
async function api(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function show(r){last=r;$('download').disabled=false;$('result').hidden=false;$('metrics').replaceChildren();for(const [key,value]of Object.entries(r.metrics)){const div=document.createElement('div');div.className='metric';div.append(text('strong',fmt(value)),text('span',key));$('metrics').append(div);}$('limitations').replaceChildren(...r.limitations.map(s=>text('p',s)));$('comparison').textContent=JSON.stringify(r.policies||r.models||r.selection_record||{note:'See the metric definitions and source model.'},null,2);const rows=r.rows.slice(0,100),fields=rows.length?Object.keys(rows[0]):[];$('table').replaceChildren();const head=document.createElement('tr');fields.forEach(k=>head.append(text('th',k)));$('table').append(head);for(const row of rows){const tr=document.createElement('tr');fields.forEach(k=>tr.append(text('td',fmt(row[k]))));$('table').append(tr);}$('command').textContent=r.experiment==='fit-passive'?'python run.py fit --data examples/passive_step.csv --metadata examples/passive_source.json --out runs/my-fit':`python run.py run ${r.experiment} --out runs/${r.experiment}-01\npython run.py replay runs/${r.experiment}-01\n\nCustom parameters: save the following JSON as parameters.json, then add --params parameters.json\n`+JSON.stringify(r.parameters,null,2);draw(r);}
function draw(r){const svg=$('chart');svg.replaceChildren();$('legend').replaceChildren();$('chart-wrap').hidden=!r.series;if(!r.series)return;const sx=r.series.x,ys=r.series.y;const rows=r.rows.filter(v=>Number.isFinite(v[sx]));if(!rows.length)return;const vals=rows.flatMap(v=>ys.map(y=>v[y]).filter(Number.isFinite));if(!vals.length)return;let xmin=rows[0][sx],xmax=rows.at(-1)[sx],ymin=Math.min(...vals),ymax=Math.max(...vals);if(xmin===xmax)xmax=xmin+1;if(ymin===ymax)ymax=ymin+1;const ypad=(ymax-ymin)*.08;ymin-=ypad;ymax+=ypad;const ns='http://www.w3.org/2000/svg';const node=(tag,attrs)=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);return n;};const X=x=>65+(x-xmin)/(xmax-xmin)*810,Y=y=>280-(y-ymin)/(ymax-ymin)*245;for(let i=0;i<5;i++){const y=ymin+(ymax-ymin)*i/4;node('line',{x1:65,x2:875,y1:Y(y),y2:Y(y),stroke:'#dce5ed'});const t=node('text',{x:55,y:Y(y)+4,'text-anchor':'end','font-size':11,fill:'#526678'});t.textContent=fmt(y);}const colors=['#137b83','#bd553c','#645ba0','#62812d'];ys.forEach((key,i)=>{let points=[];const stride=Math.max(1,Math.ceil(rows.length/600));rows.forEach((row,j)=>{if((j%stride===0||j===rows.length-1)&&Number.isFinite(row[key]))points.push(`${X(row[sx])},${Y(row[key])}`);});node('polyline',{points:points.join(' '),fill:'none',stroke:colors[i%4],'stroke-width':2});const label=text('span',key);label.style.borderColor=colors[i%4];$('legend').append(label);});const label=node('text',{x:470,y:315,'text-anchor':'middle','font-size':13,fill:'#526678'});label.textContent=`${sx}: ${fmt(xmin)} to ${fmt(xmax)}`;}
$('run').onclick=async()=>{if(!$('parameters').reportValidity())return;const parameters={};for(const input of $('parameters').querySelectorAll('input'))parameters[input.name]=Number(input.value);$('error').textContent='';$('run').disabled=true;$('status').textContent='Computing locally…';try{show(await api('/api/run',{experiment:selected,parameters}));$('status').textContent='Computed · not clinical evidence';}catch(e){$('error').textContent=e.message;$('status').textContent='Rejected / failed';}finally{$('run').disabled=false;}};
$('reset').onclick=()=>select(selected);$('filter').oninput=menu;$('parameters').onsubmit=e=>{e.preventDefault();$('run').click();};
$('download').onclick=()=>{if(!last)return;const url=URL.createObjectURL(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${last.experiment}-result.json`;a.click();URL.revokeObjectURL(url);};
$('fit-tab').onclick=()=>{$('book-workspace').hidden=true;$('workspace').hidden=true;$('fit-workspace').hidden=false;$('result').hidden=true;};
$('metadata').value=JSON.stringify({source_kind:'synthetic',source_locator:'Local synthetic passive step',license:'CC0-1.0',time_unit:'ms',voltage_unit:'mV',current_pA:100,rest_mV:-65,onset_ms:0},null,2);
$('fit-run').onclick=async()=>{try{$('fit-error').textContent='';const file=$('csv-file').files[0];if(!file)throw Error('Choose a CSV recording.');show(await api('/api/fit',{csv:await file.text(),metadata:JSON.parse($('metadata').value)}));}catch(e){$('fit-error').textContent=e.message;}};
fetch('/api/catalog').then(r=>r.json()).then(x=>{labs=x;select(selected);}).catch(e=>{$('error').textContent='Start the local Python server to use this workbench. '+e.message;});

$('book-tab').onclick=()=>{$('book-workspace').hidden=false;$('workspace').hidden=true;$('fit-workspace').hidden=true;$('result').hidden=true;};
fetch('/api/book').then(r=>r.json()).then(book=>{for(const chapter of book.chapters){const b=text('button',`Chapter ${chapter.chapter} · ${chapter.english_title}`);b.className='secondary';b.dataset.chapter=chapter.chapter;b.append(text('small',`${chapter.primary_experiment} · sections ${chapter.section_anchors.join(', ')}`));b.onclick=()=>select(chapter.primary_experiment);$('chapter-cards').append(b);}});
